# Generated by Django 5.2.6 on 2026-09-21 17:24

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('SALARY', 'Salary Account')], default='SAVINGS', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('ifsc_code', models.CharField(default='BANKFL0001234', max_length=20)),
                ('branch', models.CharField(default='BankFlow Demo Branch', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(default=banking.models.default_loan_id, max_length=30, unique=True)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('EDUCATION', 'Education Loan'), ('VEHICLE', 'Vehicle Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=9.5, max_digits=5)),
                ('tenure_months', models.PositiveIntegerField(default=12)),
                ('emi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PENDING', max_length=12)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employment_type', models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed'), ('STUDENT', 'Student'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], default='SALARIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('TRANSACTION', 'Transaction'), ('LOAN', 'Loan'), ('SECURITY', 'Security'), ('SUMMARY', 'Summary'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=banking.models.default_transaction_id, max_length=30, unique=True)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Food', 'Food'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Transfer', 'Transfer'), ('Other', 'Other')], default='Other', max_length=20)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='COMPLETED', max_length=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
